spring.application.name=recommendation

# PRIMARY DATASOURCE
spring.datasource.url=jdbc:h2:mem:appdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

# SECONDARY DATASOURCE
application.recommendations-db.url=jdbc:h2:file:./transactiondb;DB_CLOSE_ON_EXIT=FALSE
application.recommendations-db.driver-class-name=org.h2.Driver
application.recommendations-db.username=sa
application.recommendations-db.password=

# Data initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# Build Info
spring.info.build.enabled=true

# App version
app.version=0.0.1-SNAPSHOT


logging.level.com.bank.star.star=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG


# Telegram Bot Configuration
telegram.bot.enabled=true
telegram.bot.name=star_bank_recommendations_bot
telegram.bot.username=star_bank_recommendations_bot
telegram.bot.token=8253067700:AAE-jj3vJOvuCwYMDTXQo6fFEZby4ogsEhs

# ????????? JAXB ??? Jackson ? Hibernate
spring.jpa.properties.hibernate.xml_mapping_enabled=false
